# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gliar_wrappers", use_symbols = TRUE, package_name = "gliar")

#' @docType package
#' @usage NULL
#' @useDynLib gliar, .registration = TRUE
NULL

push_telemetry <- function(json_payload, url, timeout) .Call(wrap__push_telemetry, json_payload, url, timeout)


# nolint end
