# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_gliar_wrappers", use_symbols = TRUE, package_name = "gliar")

#' @docType package
#' @usage NULL
#' @useDynLib gliar, .registration = TRUE
NULL

#' @export
enqueue_to_background <- function(json_payload, url, timeout) .Call(wrap__enqueue_to_background, json_payload, url, timeout)

#' @export
flush_queue <- function() .Call(wrap__flush_queue)

#' @export
trigger_panic <- function() invisible(.Call(wrap__trigger_panic))


# nolint end
