[settings]
experimental = true
lockfile     = true

[tools]
gum    = "0.17.0"
python = "3.10.0"
r      = "4.4.1"
ruff   = "0.14.8"
uv     = "0.9.17"
rust   = "1.93.0"
pandoc = "3.6.3"
cmake  = "3.31.5"

[env]
_.file        = [".env", ".env.r"]
_.path        = ["./scripts"]
PYTHONPATH    = "{{config_root}}/scripts:$PYTHONPATH"
VERSION       = "0.1.0"
GLIA_DEV_MODE = true

RENV_CONFIG_PAK_ENABLED    = true
RENV_PATHS_LIBRARY         = "renv/library"
RENV_CONFIG_REPOS_OVERRIDE = "https://cloud.r-project.org"

API_HOST       = "localhost"
API_PORT       = "8000"
POSTGRES_PORT  = "5432"
POSTGRES_HOST  = "localhost"
GLIA_API_URL = "http://{{ env.API_HOST }}:{{ env.API_PORT }}/ingest"

CORE_QUEUE_LIMIT = "1000"
CORE_BATCH_SIZE = "1000"
CORE_BATCH_TIMEOUT_SEC = "2"
CORE_FLUSH_TIMEOUT_SEC = "5"

PERFORMANCE_TESTING = true

[tasks.alembic]
description = "Internal helper for alembic commands"
run         = "uv run alembic -c backend/alembic.ini"
