[tasks."lint:gliar"]
description = "Lint R package using lintr"
dir         = "gliar"
run         = "Rscript -e 'lints <- lintr::lint_package(); print(lints); if (length(lints) > 0) q(status = 1)'"

[tasks."lint:python"]
description = "Lint Python code using ruff"
run         = "ruff check ."

[tasks.lint]
description = "Run all linters"
run         = "mise run lint:python && mise run lint:gliar"
