#!/bin/bash
#MISE description="Poll the API until it responds"
MAX_TRIES=15
COUNT=0
until mise run api:status > /dev/null 2>&1; do
  COUNT=$((COUNT + 1))
  if [ $COUNT -ge $MAX_TRIES ]; then
    mise run api:status
    exit 1
  fi
  printf "."
  sleep 1
done
echo "\n[SUCCESS] API is ready."
