#!/bin/bash
#MISE description="Vendor glia_core into the R package using rsync"
#MISE dir="gliar"
#MISE sources=["../glia_core/src/**/*.rs", "../glia_core/Cargo.toml"]
mkdir -p src/glia_core
rsync -a --delete \
    --exclude 'target' \
    --exclude '.git' \
    ../glia_core/ src/glia_core/
