#!/bin/bash
#MISE description = "Sync R dependencies from DESCRIPTION using renv + pak"
#MISE dir = "glia-gliar"
#MISE sources = ["DESCRIPTION"]
#MISE outputs = ["renv.lock"]

Rscript -e '
  options(repos = c(CRAN = "https://cloud.r-project.org"))
  
  # .Library installs to where R is intalled, in this case, within the mise structure
  if (!requireNamespace("renv", quietly = TRUE)) {
    install.packages("renv", lib = .Library, repos = "https://cloud.r-project.org")
  }

  options(renv.config.pak.enabled = TRUE)
  renv::consent(provided = TRUE)
  
  #    renv automatically detects the project root and creates/uses the local "renv/library".
  renv::install(dependencies = TRUE)
  renv::snapshot(prompt = FALSE)
'