"""

Revision ID: 0c69793f9b18
Revises: 5693cef380bf
Create Date: 2026-03-11 12:11:29.047601

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0c69793f9b18'
down_revision: str | Sequence[str] | None = '5693cef380bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
