"""

Revision ID: 476c9650b98e
Revises: 0c69793f9b18
Create Date: 2026-03-11 23:01:56.564883

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '476c9650b98e'
down_revision: str | Sequence[str] | None = '0c69793f9b18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
