"""indexing jobs_started_at

Revision ID: 5693cef380bf
Revises: 6eeb89a12e02
Create Date: 2026-03-11 12:11:12.236648

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5693cef380bf'
down_revision: str | Sequence[str] | None = '6eeb89a12e02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_started_at'), 'jobs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_started_at'), table_name='jobs')
    # ### end Alembic commands ###
