"""

Revision ID: 67b655d2cca0
Revises: 476c9650b98e
Create Date: 2026-03-11 23:10:46.797965

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '67b655d2cca0'
down_revision: str | Sequence[str] | None = '476c9650b98e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
