"""rename wall_time and rss fields

Revision ID: 69d02211b0b2
Revises: a7be2476bf1f
Create Date: 2026-04-06 19:39:18.894948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '69d02211b0b2'
down_revision: Union[str, Sequence[str], None] = 'a7be2476bf1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('wall_time_ms', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('max_rss_kb', sa.Integer(), nullable=False))
    op.drop_column('jobs', 'max_rss_mb')
    op.drop_column('jobs', 'wall_time_sec')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('wall_time_sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('max_rss_mb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('jobs', 'max_rss_kb')
    op.drop_column('jobs', 'wall_time_ms')
    # ### end Alembic commands ###
