"""promote_system_metrics

Revision ID: 6eeb89a12e02
Revises: bceadc807baa
Create Date: 2026-01-13 18:24:40.524230

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6eeb89a12e02"
down_revision: str | Sequence[str] | None = "bceadc807baa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("hostname", sqlmodel.AutoString(), nullable=False))
    op.add_column("jobs", sa.Column("os_info", sqlmodel.AutoString(), nullable=False))
    op.add_column(
        "jobs", sa.Column("script_path", sqlmodel.AutoString(), nullable=True)
    )
    op.add_column(
        "jobs",
        sa.Column("argv", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("jobs", sa.Column("wall_time_sec", sa.Float(), nullable=False))
    op.alter_column(
        "jobs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "jobs",
        "ended_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.create_index(op.f("ix_jobs_hostname"), "jobs", ["hostname"], unique=False)
    op.create_index(op.f("ix_jobs_user_name"), "jobs", ["user_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_user_name"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_hostname"), table_name="jobs")
    op.alter_column(
        "jobs",
        "ended_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "jobs",
        "started_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_column("jobs", "wall_time_sec")
    op.drop_column("jobs", "argv")
    op.drop_column("jobs", "script_path")
    op.drop_column("jobs", "os_info")
    op.drop_column("jobs", "hostname")
    # ### end Alembic commands ###
