"""

Revision ID: a7be2476bf1f
Revises: 67b655d2cca0
Create Date: 2026-03-11 23:13:32.077216

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'a7be2476bf1f'
down_revision: str | Sequence[str] | None = '67b655d2cca0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
