"""init_jobs_table

Revision ID: bceadc807baa
Revises:
Create Date: 2026-01-06 22:55:44.047581

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bceadc807baa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("program_name", sqlmodel.AutoString(), nullable=False),
        sa.Column("user_name", sqlmodel.AutoString(), nullable=False),
        sa.Column("script_sha256", sqlmodel.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=False),
        sa.Column("exit_code_int", sa.Integer(), nullable=False),
        sa.Column("cpu_time_sec", sa.Float(), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=False),
        sa.Column("max_rss_mb", sa.Float(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_jobs_program_name"), "jobs", ["program_name"], unique=False
    )
    op.create_index(op.f("ix_jobs_run_id"), "jobs", ["run_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_run_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_program_name"), table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
